'use client'

import type { WarmOutreachChannel } from '@/lib/warm-outreach-relationship-intelligence'
import type { RelationshipPacketApiResponse } from './RelationshipPacketPanel'

export const WARM_SLACK_SEND_APPROVAL_QA_CONTACT_ID = 42
export const WARM_SLACK_SEND_APPROVAL_QA_QUEUE_ID = 'qa-warm-slack-send-approval-queue-42'
export const WARM_SLACK_SEND_APPROVAL_QA_MESSAGE_VERSION_KEY =
  'warm-outreach:email-message-version:v1:qa-warm-slack-send-approval'

const timestamp = '2026-08-27T12:00:00.000Z'

export const warmSlackSendApprovalQaLead = {
  id: WARM_SLACK_SEND_APPROVAL_QA_CONTACT_ID,
  name: 'Amina QA Recipient',
  email: 'amina.qa@example.test',
  company: 'Portfolio QA Workspace',
  company_domain: 'qa.amadutown.test',
  job_title: 'Operations Director',
  industry: 'Professional Services',
  phone_number: null,
  lead_source: 'warm_referral',
  lead_score: 91,
  outreach_status: 'draft',
  qualification_status: 'qualified',
  created_at: timestamp,
  linkedin_url: null,
  ai_readiness_score: null,
  competitive_pressure_score: null,
  quick_wins: null,
  message: null,
  full_report: null,
  rep_pain_points: null,
  messages_count: 1,
  messages_sent: 0,
  has_reply: false,
  has_sales_conversation: false,
  latest_session_id: null,
  session_count: 1,
  evidence_count: 3,
  last_vep_triggered_at: null,
  last_vep_status: null,
  last_n8n_outreach_triggered_at: null,
  last_n8n_outreach_status: null,
  last_n8n_outreach_template_key: null,
  has_extractable_text: false,
  recent_email_drafts: [
    {
      id: WARM_SLACK_SEND_APPROVAL_QA_QUEUE_ID,
      subject: 'Follow-up from the Portfolio QA workspace',
      status: 'draft',
      created_at: timestamp,
      email_message_id: 'qa-gmail-message-42',
    },
  ],
}

function sendAuthority(
  mode: 'warm_1_to_1' | 'warm_1_to_many',
  channel: WarmOutreachChannel,
  state: 'eligible_for_future_activation' | 'manual_only',
) {
  return {
    version: 'warm-outreach-send-authority/v1',
    mode,
    channel,
    label: `${channel} ${state}`,
    state,
    futureActivationEligible: state === 'eligible_for_future_activation',
    externalSendApproved: false,
    externalSendEnabled: false,
    providerExecutionEnabled: false,
    gmailDraftCreationEnabled: false,
    schedulingEnabled: false,
    outcomeTrackingEnabled: false,
    humanApprovalRequired: true,
    idempotencyKey: `warm-outreach:send-readiness:v1:qa:${mode}:${channel}`,
    gates: [
      'target_source_provenance',
      'relationship_basis',
      'consent_suppression',
      'personalization',
      'human_approval',
      'provider_capability',
      'idempotency',
      'send_scheduling',
      'outcome_tracking',
      'response_follow_up',
    ].map((key) => ({
      key,
      label: key.replace(/_/g, ' '),
      status: key === 'provider_capability' && state === 'manual_only' ? 'manual_required' : 'future_gate',
      requiredForActivation: true,
      detail: 'QA fixture gate only; no provider execution is enabled.',
      externalExecutionEnabled: false,
    })),
    blockers: [],
    manualSteps: state === 'manual_only' ? ['Review this manual channel outside provider execution.'] : [],
    nextReviewAction:
      state === 'manual_only'
        ? 'Manual-only channel: prepare an operator review packet; no provider action is available.'
        : 'Prepare send packet for a future approval request; external sends remain disabled.',
  }
}

const realRecipientRolloutReadiness = {
  version: 'warm-outreach-real-gmail-rollout-readiness/v1',
  state: 'ready_for_send_request',
  label: 'Ready for one-step send approval request',
  eligibleForSendApprovalRequest: true,
  canBuildSlackApprovalPayload: true,
  exactNextAction: 'approve_send_request',
  actionLabel: 'Approve send request',
  requirements: {
    draftEvidence: {
      state: 'tracked',
      draftId: 'qa-gmail-draft-42',
      threadId: 'qa-gmail-thread-42',
      messageId: 'qa-gmail-message-42',
      sourceIds: [WARM_SLACK_SEND_APPROVAL_QA_QUEUE_ID],
      detail: 'Tracked Gmail draft evidence is present. This is the message to approve; it is not a send.',
    },
    senderMatch: {
      state: 'matched',
      requiredSender: 'hello@amadutown.com',
      connectedAs: 'hello@amadutown.com',
      detail: 'Tracked draft sender matches the required AmaduTown sender.',
    },
    suppression: {
      state: 'clear',
      reasons: [],
      detail: 'No suppression blocker is recorded.',
    },
    provider: {
      state: 'configured',
      detail: 'Gmail provider configuration is present for readiness review; this contract still does not call Gmail.',
    },
    authorization: {
      state: 'missing',
      decisionKey: null,
      detail: 'No Portfolio or Slack send authorization decision is recorded yet.',
    },
    submittedEvidence: {
      state: 'missing',
      sourceIds: [],
      detail: 'No submitted send evidence is recorded for this contact, channel, and message version.',
    },
    execution: {
      state: 'approval_needed',
      sourceIds: [],
      detail: 'No send approval is recorded yet. Build the one-recipient approval request first.',
    },
  },
  blockers: [],
  auditReceipt: {
    version: 'warm-gmail-canary-proof-receipt/v1',
    queueRow: {
      sourceId: WARM_SLACK_SEND_APPROVAL_QA_QUEUE_ID,
      contactId: WARM_SLACK_SEND_APPROVAL_QA_CONTACT_ID,
      relationshipPacketReference: `contact_submission:${WARM_SLACK_SEND_APPROVAL_QA_CONTACT_ID}:${warmSlackSendApprovalQaLead.name}`,
      messageVersionKey: WARM_SLACK_SEND_APPROVAL_QA_MESSAGE_VERSION_KEY,
      sendQueueIdempotencyKey: 'warm-outreach:email-send-queue:v1:qa-warm-slack-send-approval',
      submittedEvidenceKey: 'warm-outreach:email-submitted-evidence:v1:qa-warm-slack-send-approval',
    },
    recipientIdentity: {
      channel: 'email',
      requiredSender: 'hello@amadutown.com',
      connectedAs: 'hello@amadutown.com',
      senderState: 'matched',
    },
    approvalEvidence: {
      slackApprovalStatus: 'not_sent',
      slackDispatchStatus: 'not_sent',
      portfolioAuthorizationState: 'missing',
      decisionKey: null,
      recordsAuthorizationIntentOnly: true,
      gmailSendCalledByApproval: false,
    },
    draftEvidence: {
      state: 'tracked',
      draftId: 'qa-gmail-draft-42',
      threadId: 'qa-gmail-thread-42',
      messageId: 'qa-gmail-message-42',
      sourceIds: [WARM_SLACK_SEND_APPROVAL_QA_QUEUE_ID],
      detail: 'Tracked Gmail draft evidence is present. This is the message to approve; it is not a send.',
    },
    suppressionAndIdempotency: {
      suppressionState: 'clear',
      suppressionReasons: [],
      duplicateDetected: false,
      submittedEvidenceRecorded: false,
    },
    gmailCapability: {
      providerState: 'configured',
      providerDetail: 'Gmail provider configuration is present for readiness review; this contract still does not call Gmail.',
      senderDetail: 'Tracked draft sender matches the required AmaduTown sender.',
    },
    finalSendAuthority: {
      state: 'awaiting_authorization',
      liveSendActionEnabled: false,
      detail: 'Readiness is prepared for an approval request, not Gmail execution.',
      nextStep:
        'Request send approval for this exact queue row from the relationship packet; Portfolio records intent only and Gmail send stays disabled.',
    },
    lastActionEvidence: {
      status: 'approval_needed',
      sourceIds: [],
      detail: 'No prior execution evidence is recorded for this contact, channel, and message version.',
      repairRequired: false,
    },
  },
  slackApprovalContract: {
    route: '/api/admin/outreach/[id]/slack-send-approval',
    method: 'POST',
    dispatchEnabled: false,
    actionIds: ['warm_gmail_send.approve', 'warm_gmail_send.reject', 'warm_gmail_send.revise'],
    payloadDedupeKey: 'warm-outreach:slack-gmail-send-card:v1:qa-warm-slack-send-approval',
    status: 'not_sent',
    requestKey: null,
    slackDispatchStatus: 'not_sent',
    recordsAuthorizationIntentOnly: true,
    gmailSendCalled: false,
    providerExecutionEnabled: false,
    approvalRequestRecovery: {
      status: 'portfolio_request_available_slack_dispatch_disabled',
      label: 'Portfolio recovery path',
      detail:
        'Slack dispatch is disabled. The relationship packet can still record a local one-recipient approval request without posting to Slack or calling Gmail.',
      nextAction:
        'Use Request send approval in this contact workroom, then record approve, reject, or revise before any separate Gmail send execution gate.',
    },
  },
  executionBoundary: {
    slackDispatch: false,
    gmailSend: false,
    providerCalls: false,
    productionEnvChange: false,
    perRecipientExecutionAuthorizationRequired: true,
    captainFlagRequiredForExecution: true,
  },
}

const gmailProviderExecutionReadiness = {
  version: 'warm-outreach-gmail-provider-execution-readiness/v1',
  state: 'approval_needed',
  label: 'One-recipient approval needed',
  liveExecutionEnabled: false,
  providerCallsEnabled: false,
  externalSendEnabled: false,
  adminActivationGate: {
    key: 'ENABLE_WARM_GMAIL_SEND_EXECUTION',
    state: 'disabled',
    detail:
      'The relationship packet and workroom never enable Gmail execution. If production execution is required, this admin/provider gate must be intentionally enabled outside the operator review surface and then disabled again after the exact one-recipient run.',
  },
  operatorDecision: {
    status: 'not_sent',
    nextAction:
      'Review the recipient, relationship context, and draft, then approve, reject, or request revision from Portfolio or Slack.',
    approvalRoute: '/api/admin/outreach/[id]/slack-send-approval',
    recordsAuthorizationIntentOnly: true,
  },
  exactExecutionGate: {
    route: '/api/admin/outreach/[id]/gmail-user-send',
    method: 'POST',
    enabledOnThisSurface: false,
    sendAuthorization: 'execute_warm_gmail_send_for_authorized_recipient',
    messageVersionKey: WARM_SLACK_SEND_APPROVAL_QA_MESSAGE_VERSION_KEY,
    sendQueueIdempotencyKey: 'warm-outreach:email-send-queue:v1:qa-warm-slack-send-approval',
    submittedEvidenceKey: 'warm-outreach:email-submitted-evidence:v1:qa-warm-slack-send-approval',
    detail:
      'The execution route still requires exact per-recipient request keys, approved Portfolio authorization, draft evidence, sender match, suppression clearance, idempotency checks, and the admin activation gate.',
  },
  canaryTrace: {
    queueId: WARM_SLACK_SEND_APPROVAL_QA_QUEUE_ID,
    status: 'approval_needed',
    sentEvidenceRecorded: false,
    gmailMessageId: null,
    gmailThreadId: null,
    detail: 'No prior execution evidence is recorded for this contact, channel, and message version.',
  },
}

const emailLifecycle = {
  version: 'warm-outreach-email-send-lifecycle/v1',
  contactId: WARM_SLACK_SEND_APPROVAL_QA_CONTACT_ID,
  mode: 'warm_1_to_1',
  channel: 'email',
  label: 'Email is first candidate, provider/send activation blocked',
  state: 'blocked_before_provider_activation',
  firstCandidateChannel: true,
  sendReady: false,
  providerExecutionEnabled: false,
  externalSendEnabled: false,
  gmailDraftCreationEnabled: false,
  schedulingEnabled: false,
  messageVersionKey: WARM_SLACK_SEND_APPROVAL_QA_MESSAGE_VERSION_KEY,
  sendQueueIdempotencyKey: 'warm-outreach:email-send-queue:v1:qa-warm-slack-send-approval',
  providerCapabilitySmokeKey: 'warm-outreach:gmail-capability-smoke:v1:qa-warm-slack-send-approval',
  gmailDraftCreationGateKey: 'warm-outreach:gmail-draft-creation-gate:v1:qa-warm-slack-send-approval',
  submittedEvidenceKey: 'warm-outreach:email-submitted-evidence:v1:qa-warm-slack-send-approval',
  gmailDraftHandoffPacket: {
    version: 'warm-outreach-gmail-draft-handoff/v1',
    state: 'ready_for_internal_handoff',
    label: 'Internal Gmail draft handoff ready',
    internalHandoffReady: true,
    channel: 'email',
    contactReference: {
      contactId: WARM_SLACK_SEND_APPROVAL_QA_CONTACT_ID,
      contactName: warmSlackSendApprovalQaLead.name,
      reference: `contact_submission:${WARM_SLACK_SEND_APPROVAL_QA_CONTACT_ID}:${warmSlackSendApprovalQaLead.name}`,
    },
    messageVersionKey: WARM_SLACK_SEND_APPROVAL_QA_MESSAGE_VERSION_KEY,
    templateDraftBasis: {
      recommendedTemplate: 'follow_up',
      selectedChannel: 'email',
      relationshipEventId: 'qa-meeting-42',
      detail: 'Use follow up as the internal draft basis for the current message version.',
    },
    provenanceSummary: {
      relationshipSourceCount: 3,
      relationshipSignalCount: 3,
      safeToMentionCount: 2,
      summarizeOnlyCount: 1,
      commonalityCount: 2,
      detail: 'Portfolio-local relationship provenance is summarized for the handoff packet.',
    },
    suppressionStatus: 'clear',
    suppressionReasons: [],
    idempotencyKey: 'warm-outreach:gmail-draft-handoff:v1:qa-warm-slack-send-approval',
    futureApprovalGates: [
      'human_reply_or_draft_approval',
      'provider_capability_smoke',
      'gmail_draft_creation_authority',
      'external_send_authority',
      'send_scheduling',
      'submitted_sent_evidence',
    ],
    gmailProviderActivated: false,
    gmailDraftCreationEnabled: false,
    providerCallsEnabled: false,
    externalSendBlocked: true,
    detail: 'Operator can review the internal Gmail draft handoff packet; Gmail draft creation and send stay blocked.',
  },
  providerCapabilitySmoke: {
    version: 'warm-outreach-gmail-provider-smoke/v1',
    provider: 'gmail',
    status: 'smoke_passed',
    label: 'Read-only Gmail smoke passed',
    smokeKey: 'warm-outreach:gmail-capability-smoke:v1:qa-warm-slack-send-approval',
    oauthConfigured: true,
    connectedProfileAvailable: true,
    providerConfigured: true,
    readOnlySmokeReady: false,
    readOnlySmokeEnabled: false,
    providerCallsEnabled: false,
    externalSendEnabled: false,
    gmailDraftCreationEnabled: false,
    requiredConfig: ['QA fixture only'],
    blockedReasons: [],
    lastSmokeAt: timestamp,
    lastSmokeError: null,
    futureActivationGate:
      'A later captain-lane approval must authorize any Gmail provider smoke; this scaffold records readiness only.',
    notes: [
      'This QA model does not call Gmail.',
      'Slack action, Gmail draft creation, send, scheduling, and provider calls remain disabled.',
    ],
  },
  gmailDraftCreationGate: {
    version: 'warm-outreach-gmail-draft-creation-gate/v1',
    status: 'ready_for_disabled_activation',
    label: 'Ready for disabled Gmail draft creation activation',
    draftCreationKey: 'warm-outreach:gmail-draft-creation-gate:v1:qa-warm-slack-send-approval',
    internalHandoffReady: true,
    providerSmokeStatus: 'smoke_passed',
    providerSmokePassed: true,
    draftCreationAuthority: true,
    gmailDraftCreationEnabled: false,
    providerCallsEnabled: false,
    externalSendEnabled: false,
    externalSendBlocked: true,
    blockedReasons: [],
    requiredGates: [
      'internal_gmail_draft_handoff',
      'read_only_gmail_provider_smoke',
      'gmail_draft_creation_authority',
      'duplicate_prevention',
      'external_send_authority_separate_future_gate',
    ],
    notes: [
      'This gate does not create Gmail drafts.',
      'Draft creation stays disabled even when readiness evidence is complete.',
      'External send authority remains a separate future gate.',
    ],
  },
  gmailProviderActivationReadiness: {
    version: 'warm-outreach-gmail-provider-activation-readiness/v1',
    localDraftReadiness: {
      state: 'ready',
      label: 'Local draft handoff ready',
      detail: 'Operator can review the internal Gmail draft handoff packet; Gmail draft creation and send stay blocked.',
      idempotencyKey: 'warm-outreach:gmail-draft-handoff:v1:qa-warm-slack-send-approval',
    },
    connectedSenderReadiness: {
      state: 'ready_for_live_canary',
      label: 'Connected sender matched',
      requiredSender: 'hello@amadutown.com',
      connectedAs: 'hello@amadutown.com',
      recoveryAction: 'No recovery needed for this QA fixture.',
    },
    liveDraftCanaryReadiness: {
      state: 'passed_no_send',
      label: 'No-send canary passed',
      detail: 'Synthetic no-send evidence is present for QA only.',
      providerCallsEnabled: false,
      gmailDraftCreated: false,
      trackingPersisted: false,
      externalSendEnabled: false,
    },
    duplicateDraftEvidence: {
      createdOnce: true,
      duplicatePrevented: true,
      draftId: 'qa-gmail-draft-42',
      threadId: 'qa-gmail-thread-42',
      messageId: 'qa-gmail-message-42',
      sourceIds: [WARM_SLACK_SEND_APPROVAL_QA_QUEUE_ID],
      noSendStatus: 'no_send',
      detail: 'Existing Gmail draft metadata is present for QA review only.',
    },
    externalSendBoundary: {
      blocked: true,
      label: 'External send blocked',
      detail:
        'Gmail draft creation and Gmail send authority are separate gates. A draft, smoke, or canary never authorizes sending.',
    },
    remainingHumanGates: [
      'review_local_draft_handoff_packet',
      'verify_connected_sender_identity',
      'explicit_per_recipient_gmail_draft_authorization',
      'captain_enable_exact_execution_gate',
      'separate_external_send_authority',
    ],
  },
  externalSendReadiness: {
    version: 'warm-outreach-external-send-readiness/v1',
    state: 'blocked_pending_authority',
    label: 'External Gmail send authority blocked',
    senderIdentity: {
      state: 'verified_for_draft_only',
      requiredSender: 'hello@amadutown.com',
      connectedAs: 'hello@amadutown.com',
      detail: 'Sender identity is verified for draft-only QA readiness.',
    },
    recipientApproval: {
      state: 'required',
      contactId: WARM_SLACK_SEND_APPROVAL_QA_CONTACT_ID,
      approved: false,
      detail: 'No external-send approval is recorded. This QA click records Slack approval-request intent only.',
    },
    draftEvidence: {
      state: 'tracked',
      gmailDraftExists: true,
      draftId: 'qa-gmail-draft-42',
      threadId: 'qa-gmail-thread-42',
      messageId: 'qa-gmail-message-42',
      sourceIds: [WARM_SLACK_SEND_APPROVAL_QA_QUEUE_ID],
      detail: 'A Gmail draft exists as tracking evidence only. It does not grant send authority.',
    },
    suppressionConsent: {
      state: 'clear',
      reasons: [],
      detail: 'No suppression blocker is recorded, but explicit per-recipient send approval is still required.',
    },
    idempotency: {
      messageVersionKey: WARM_SLACK_SEND_APPROVAL_QA_MESSAGE_VERSION_KEY,
      sendQueueIdempotencyKey: 'warm-outreach:email-send-queue:v1:qa-warm-slack-send-approval',
      submittedEvidenceKey: 'warm-outreach:email-submitted-evidence:v1:qa-warm-slack-send-approval',
      duplicateDetected: true,
      detail: 'Future external-send review must reuse the stable contact/channel/message-version keys.',
    },
    externalSend: {
      enabled: false,
      approved: false,
      blocked: true,
      detail:
        'Portfolio cannot send this Gmail message from this state. Gmail drafts, canaries, and provider smoke evidence are not send permission.',
      nextStep:
        'Ask the Integration Captain for explicit per-recipient external-send authority after sender identity, suppression, draft evidence, and final copy are reviewed.',
    },
  },
  realRecipientRolloutReadiness,
  gmailProviderExecutionReadiness,
  duplicatePrevention: {
    scope: 'contact_channel_message_version',
    duplicateDetected: true,
    existingEvidenceIds: [WARM_SLACK_SEND_APPROVAL_QA_QUEUE_ID],
    requiredUniqueKeys: [
      WARM_SLACK_SEND_APPROVAL_QA_MESSAGE_VERSION_KEY,
      'warm-outreach:gmail-draft-handoff:v1:qa-warm-slack-send-approval',
      'warm-outreach:gmail-draft-creation-gate:v1:qa-warm-slack-send-approval',
      'warm-outreach:email-send-queue:v1:qa-warm-slack-send-approval',
      'warm-outreach:gmail-capability-smoke:v1:qa-warm-slack-send-approval',
      'warm-outreach:email-submitted-evidence:v1:qa-warm-slack-send-approval',
    ],
    detail: 'Future send activation must reuse these keys to prevent duplicate contact/channel/message-version execution.',
  },
  suppressionCheck: {
    status: 'clear',
    reasons: [],
  },
  relationshipProvenance: {
    status: 'present',
    sourceCount: 3,
    signalCount: 3,
    relationshipEventId: 'qa-meeting-42',
    detail: 'Portfolio-local relationship provenance is attached.',
  },
  personalizationProvenance: {
    status: 'present',
    safeToMentionCount: 2,
    summarizeOnlyCount: 1,
    commonalityCount: 2,
    detail: 'Personalization context is available from local evidence.',
  },
  auditState: {
    status: 'scaffold_only',
    notes: [
      'Email is the first candidate channel for future activation review.',
      'No Gmail draft, Gmail send, provider smoke, schedule, or submitted evidence mutation is enabled.',
      'A later explicit provider/send approval gate is required before any external action.',
    ],
  },
  stages: [
    {
      key: 'draft_packet',
      label: 'Draft packet',
      status: 'ready_for_review',
      detail: 'Local relationship and personalization context can be reviewed as a draft packet.',
    },
    {
      key: 'human_reply_or_draft_approval',
      label: 'Human draft approval',
      status: 'ready_for_review',
      detail: 'QA fixture records that the draft exists for review; it is still not a send.',
    },
    {
      key: 'send_authority_review',
      label: 'Send authority review',
      status: 'ready_for_review',
      detail: 'All readiness evidence is present, but Gmail execution remains disabled until human and captain gates pass.',
    },
    {
      key: 'provider_capability_smoke',
      label: 'Provider capability smoke',
      status: 'ready_for_review',
      detail: 'Synthetic smoke evidence is present; no provider call runs.',
    },
    {
      key: 'scheduled_send_queue',
      label: 'Scheduled send queue',
      status: 'disabled',
      detail: 'Scheduling is disabled until provider/send activation.',
    },
    {
      key: 'submitted_sent_evidence',
      label: 'Submitted/sent evidence',
      status: 'evidence_required',
      detail: 'Submitted or sent evidence must be recorded after a future approved provider action.',
    },
  ],
}

function readinessItem(
  mode: 'warm_1_to_1' | 'warm_1_to_many',
  channel: WarmOutreachChannel,
  state: 'eligible_for_future_activation' | 'manual_only',
) {
  return {
    version: 'warm-outreach-channel-send-readiness/v1',
    mode,
    channel,
    label: `${channel} QA send readiness`,
    state: state === 'manual_only' ? 'manual_only' : 'ready_for_review',
    sendReady: false,
    externalSendEnabled: false,
    providerExecutionEnabled: false,
    humanApprovalRequired: true,
    idempotencyKey: `warm-outreach:channel-send-readiness:v1:qa:${mode}:${channel}`,
    blockers: [],
    gatesRemaining: ['human_approval', 'provider_execution_gate', 'external_send_authority'],
    auditNotes: ['QA fixture only; no provider, Slack, Gmail, scheduling, or send execution is enabled.'],
    sendAuthority: sendAuthority(mode, channel, state),
    emailSendLifecycle: channel === 'email' && mode === 'warm_1_to_1' ? emailLifecycle : null,
  }
}

export const warmSlackSendApprovalQaRelationshipPacket = {
  packet: {
    version: 'warm-outreach-relationship/v1',
    contactId: WARM_SLACK_SEND_APPROVAL_QA_CONTACT_ID,
    contactName: warmSlackSendApprovalQaLead.name,
    objective: 'Provide a deterministic Portfolio QA path for one-recipient warm Gmail send approval review.',
    relationshipBasis:
      'Synthetic test-owned relationship evidence is present for the QA route so the operator can review the real Relationship Packet path without private data or provider calls.',
    relationshipEventId: 'qa-meeting-42',
    sourceRefs: [
      {
        sourceType: 'meeting_record',
        sourceId: 'qa-meeting-42',
        summary: 'Synthetic QA meeting summary confirms a warm follow-up context.',
        privateSource: false,
        visibility: 'portfolio_internal',
        mentionSafety: 'safe_to_mention',
        sourceStatus: 'present',
      },
      {
        sourceType: 'prior_outreach',
        sourceId: WARM_SLACK_SEND_APPROVAL_QA_QUEUE_ID,
        summary: 'Tracked QA Gmail draft row exists for one contact and one message version.',
        privateSource: false,
        visibility: 'portfolio_internal',
        mentionSafety: 'safe_to_mention',
        sourceStatus: 'present',
      },
      {
        sourceType: 'manual_note',
        sourceId: 'qa-note-42',
        summary: 'QA note marks this recipient as synthetic and test-owned.',
        privateSource: false,
        visibility: 'portfolio_internal',
        mentionSafety: 'summarize_only',
        sourceStatus: 'present',
      },
    ],
    relationshipSignals: [
      'Warm follow-up context is available.',
      'One tracked Gmail draft belongs to this recipient.',
      'Sender identity and provider readiness are represented by inert QA evidence.',
    ],
    commonalities: ['Operations improvement', 'Portfolio QA review'],
    riskFlags: [],
    sourceInventory: {
      sourceStatus: [
        { sourceType: 'meeting_records', status: 'present', detail: 'Synthetic QA meeting row.' },
        { sourceType: 'outreach_queue', status: 'present', detail: 'Synthetic draft queue row.' },
        { sourceType: 'manual_notes', status: 'present', detail: 'Synthetic QA note.' },
      ],
      safeToMention: ['Synthetic warm follow-up context', 'Tracked Gmail draft exists'],
      summarizeOnly: ['QA note is test-owned and should not be used outside QA.'],
      doNotMention: [],
    },
    openingPitchGuidance: {
      safeCommonalities: ['Operations improvement', 'Portfolio QA review'],
      openingAngle: 'Review the exact drafted follow-up and approve, reject, or request revision before any execution gate.',
      channelNotes: {
        email: 'Email is the only first-candidate channel for this QA path.',
      },
    },
    suggestedNextStep: 'Request send approval and verify the pending request state remains send-blocked.',
    avoidContext: ['Do not send Slack.', 'Do not send Gmail.', 'Do not activate providers.'],
    responseMonitoringPlan: {
      enabled: false,
      plan: 'Monitoring remains local and disabled for QA.',
      externalActivationRequired: true,
    },
    confidence: 'high',
    suppression: {
      doNotContact: false,
      unsubscribed: false,
      removedAt: null,
    },
    channelCapabilities: {
      email: {
        available: true,
        providerConfigured: true,
        supportsExternalSend: false,
        manualOnly: false,
        reason: 'Synthetic provider readiness is present, but execution is disabled.',
      },
      linkedin: {
        available: false,
        providerConfigured: false,
        supportsExternalSend: false,
        manualOnly: false,
        reason: 'Not part of this QA path.',
      },
      facebook: {
        available: true,
        providerConfigured: false,
        supportsExternalSend: false,
        manualOnly: true,
        reason: 'Manual-only channel outside this QA path.',
      },
      phone_contact: {
        available: true,
        providerConfigured: false,
        supportsExternalSend: false,
        manualOnly: true,
        reason: 'Manual-only channel outside this QA path.',
      },
    },
    preferredChannel: 'email',
  },
  readiness: {
    status: 'draft_ready',
    humanReviewRequired: true,
    selectedChannel: 'email',
    recommendedTemplate: 'follow_up',
    blockers: [],
    warnings: ['This is an inert QA fixture. It must not be used for real Slack or Gmail execution.'],
    approvalBoundary: 'draft_only_no_external_send',
  },
  contextSummary: {
    readiness_status: 'draft_ready',
    safe_to_mention: ['Synthetic warm follow-up context', 'Tracked Gmail draft exists'],
    summarize_only: ['QA note is test-owned and should not be used outside QA.'],
  },
  executionBoundary: {
    source: 'portfolio_qa_fixture',
    readOnly: true,
    providerCalls: false,
    createsDraft: false,
    externalSend: false,
    n8nDispatch: false,
    slackAction: false,
    responseMonitoring: false,
  },
  responseMonitoring: {
    version: 'warm-outreach-response-monitoring/v1',
    contactId: WARM_SLACK_SEND_APPROVAL_QA_CONTACT_ID,
    status: 'awaiting_response',
    mode: 'pending',
    label: 'awaiting response',
    expectedReplyBy: null,
    latestOutboundAt: timestamp,
    latestResponseAt: null,
    staleAfterDays: 7,
    perRecipientIdempotencyKey: 'warm-outreach:monitoring-recipient:v1:qa-warm-slack-send-approval',
    evidence: [
      {
        sourceType: 'outreach_queue',
        sourceId: WARM_SLACK_SEND_APPROVAL_QA_QUEUE_ID,
        evidenceType: 'outbound_touch',
        occurredAt: timestamp,
        summary: 'Synthetic tracked Gmail draft row for QA only.',
      },
    ],
    proposedFollowUp: {
      state: 'manual_import',
      label: 'Await manual or imported response evidence',
      description: 'No response is recorded yet. Manual import is available; provider polling remains disabled.',
      requiresHumanApproval: true,
      idempotencyKey: 'warm-outreach:monitoring-follow-up:v1:qa-warm-slack-send-approval',
    },
    providerCaptureReadiness: {
      version: 'warm-outreach-provider-response-capture-readiness/v1',
      state: 'provider_assisted_readiness',
      label: 'Provider-assisted metadata ready; polling disabled',
      responseCaptureKey: 'warm-outreach:response-capture:v1:qa-warm-slack-send-approval',
      supportedClassifications: [
        { key: 'interested', label: 'Interested', humanReviewRequired: true },
        { key: 'question', label: 'Question', humanReviewRequired: true },
        { key: 'referral', label: 'Referral', humanReviewRequired: true },
        { key: 'objection', label: 'Objection', humanReviewRequired: true },
        { key: 'not_now', label: 'Not now', humanReviewRequired: true },
        { key: 'unsubscribe_do_not_contact', label: 'Unsubscribe / do not contact', humanReviewRequired: true },
        { key: 'negative_sensitive', label: 'Negative / sensitive', humanReviewRequired: true },
        { key: 'ambiguous', label: 'Ambiguous', humanReviewRequired: true },
      ],
      providers: [
        {
          provider: 'gmail',
          channel: 'email',
          state: 'readiness_metadata_only',
          label: 'Gmail / email metadata ready',
          detail: 'Provider identifiers may be stored on a manually reviewed capture, but provider polling and import jobs remain disabled.',
          manualCaptureEnabled: true,
          providerIngestionEnabled: false,
          providerPollingEnabled: false,
          externalMonitoringEnabled: false,
          externalActionEnabled: false,
        },
        {
          provider: 'facebook',
          channel: 'facebook',
          state: 'manual_capture_only',
          label: 'Facebook manual capture only',
          detail: 'Capture the response manually in Portfolio and link it to the contact or outreach queue row.',
          manualCaptureEnabled: true,
          providerIngestionEnabled: false,
          providerPollingEnabled: false,
          externalMonitoringEnabled: false,
          externalActionEnabled: false,
        },
        {
          provider: 'phone_contact',
          channel: 'phone_contact',
          state: 'manual_capture_only',
          label: 'Phone manual capture only',
          detail: 'Capture the response manually in Portfolio and link it to the contact or outreach queue row.',
          manualCaptureEnabled: true,
          providerIngestionEnabled: false,
          providerPollingEnabled: false,
          externalMonitoringEnabled: false,
          externalActionEnabled: false,
        },
      ],
      slackAlertReadiness: {
        state: 'metadata_deeplink_only',
        label: 'Slack alert metadata only',
        deepLinkReady: true,
        dispatchEnabled: false,
        slackActionEnabled: false,
        route: '/admin/contacts/[id]',
        detail: 'Response alerts may store a Portfolio contact deep link for later review, but this surface does not post Slack messages.',
      },
    },
    operatorDecisionPaths: [
      {
        key: 'capture_response',
        label: 'Capture response',
        state: 'available',
        description: 'Record a manual or provider-assisted response as Portfolio contact communication evidence.',
        requiresHumanApproval: true,
        externalActionEnabled: false,
        idempotencyKey: 'warm-outreach:operator-decision:v1:qa-capture-response',
      },
      {
        key: 'review_reply_draft',
        label: 'Review reply draft',
        state: 'readiness_only',
        description: 'A local draft decision becomes available after response evidence is captured.',
        requiresHumanApproval: true,
        externalActionEnabled: false,
        idempotencyKey: 'warm-outreach:operator-decision:v1:qa-review-reply',
      },
      {
        key: 'suppression_proposal',
        label: 'Suppression proposal',
        state: 'readiness_only',
        description: 'Unsubscribe or do-not-contact replies create a human-gated suppression proposal; this path does not mutate suppression directly.',
        requiresHumanApproval: true,
        externalActionEnabled: false,
        idempotencyKey: 'warm-outreach:operator-decision:v1:qa-suppression',
      },
      {
        key: 'interested_task',
        label: 'Interested task path',
        state: 'readiness_only',
        description: 'Interested or sales-intent replies can create a local outreach task for the next decision; no provider execution is enabled.',
        requiresHumanApproval: true,
        externalActionEnabled: false,
        idempotencyKey: 'warm-outreach:operator-decision:v1:qa-interested-task',
      },
      {
        key: 'next_touch_timing',
        label: 'Next-touch timing',
        state: 'readiness_only',
        description: 'No response is recorded yet. Manual import is available; provider polling remains disabled.',
        requiresHumanApproval: true,
        externalActionEnabled: false,
        idempotencyKey: 'warm-outreach:operator-decision:v1:qa-next-touch',
      },
      {
        key: 'slack_alert_metadata',
        label: 'Slack alert metadata',
        state: 'readiness_only',
        description: 'A future alert may deep-link to this contact workroom, but Slack dispatch and Slack actions stay disabled.',
        requiresHumanApproval: true,
        externalActionEnabled: false,
        idempotencyKey: 'warm-outreach:operator-decision:v1:qa-slack-alert',
      },
    ],
    blockedReasons: [],
    auditNotes: [
      'Monitoring is derived from local QA rows only.',
      'No external send, provider action, Gmail draft, Slack action, n8n dispatch, or schedule is executed.',
    ],
    sendReadiness: {
      version: 'warm-outreach-send-readiness/v1',
      contactId: WARM_SLACK_SEND_APPROVAL_QA_CONTACT_ID,
      modes: {
        warm_1_to_1: [
          readinessItem('warm_1_to_1', 'email', 'eligible_for_future_activation'),
          readinessItem('warm_1_to_1', 'facebook', 'manual_only'),
          readinessItem('warm_1_to_1', 'phone_contact', 'manual_only'),
        ],
        warm_1_to_many: [
          readinessItem('warm_1_to_many', 'email', 'eligible_for_future_activation'),
          readinessItem('warm_1_to_many', 'facebook', 'manual_only'),
          readinessItem('warm_1_to_many', 'phone_contact', 'manual_only'),
        ],
      },
      executionBoundary: {
        providerExecutionEnabled: false,
        externalSendEnabled: false,
        gmailDraftCreationEnabled: false,
        schedulingEnabled: false,
        slackActionEnabled: false,
        n8nDispatchEnabled: false,
      },
    },
    executionBoundary: {
      localRowsOnly: true,
      manualImportEnabled: true,
      providerResponseImportEnabled: false,
      providerPollingEnabled: false,
      externalMonitoringEnabled: false,
      externalSendEnabled: false,
      gmailDraftCreationEnabled: false,
      linkedinActionEnabled: false,
      facebookActionEnabled: false,
      phoneActionEnabled: false,
      slackActionEnabled: false,
      n8nDispatchEnabled: false,
    },
  },
} as unknown as RelationshipPacketApiResponse
