/**
 * WhyThisDraftModal — Phase 2 traceability popover.
 *
 * Two modes (driven by the `request` prop discriminator):
 *
 *   1. `mode: 'inputs'`  → shows the structured `generation_inputs` JSON that
 *      was persisted at draft creation time, fetched via
 *      GET /api/admin/outreach/drafts/:queueId/inputs. Used by the "Why?" link
 *      next to each row in the recent-drafts list.
 *
 *   2. `mode: 'preview'` → assembles the system prompt for
 *      (lead, channel, templateKey) without invoking the LLM, fetched via
 *      GET /api/admin/outreach/leads/:id/preview-prompt. Used by the
 *      "Preview prompt" button next to each template in the channel tabs.
 *
 * Both modes render in the same drawer-style modal so admins always know
 * where to look. Drafts that pre-date Phase 2 (or were generated by the
 * deactivated n8n workflow) will surface "Trace not recorded" — that's a
 * known gap, not an error.
 */

'use client'

import { useEffect, useState } from 'react'
import { AnimatePresence, motion } from 'framer-motion'
import { Loader2, X, Copy, Check } from 'lucide-react'
import { getCurrentSession } from '@/lib/auth'
import type { OutreachChannel } from '@/lib/constants/prompt-keys'

interface GenerationInputsShape {
  template_key?: string
  prompt_version?: number | null
  channel?: string
  model?: string
  provider?: string
  temperature?: number
  max_tokens?: number
  sequence_step?: number
  research_brief_chars?: number
  social_proof_chars?: number
  meeting_summary_present?: boolean
  meeting_action_items_chars?: number
  pinecone_chars?: number
  prior_chat_present?: boolean
  pinecone_block_hash?: string | null
}

interface DraftInputsResponse {
  id: string
  contactSubmissionId: number
  channel: string
  status: string
  sequenceStep: number
  subject: string | null
  createdAt: string
  generationModel: string | null
  generationPromptSummary: string | null
  generationInputs: GenerationInputsShape | null
}

interface PreviewPromptResponse {
  channel: OutreachChannel
  templateKey: string
  sequenceStep: number
  promptVersion: number | null
  promptName: string | null
  model: string
  provider: string
  temperature: number
  maxTokens: number
  systemPrompt: string
  userPrompt: string
  contextSizes: {
    researchBriefChars: number
    socialProofChars: number
    meetingSnippetChars: number
    meetingActionItemsChars: number
    pineconeChars: number
    priorChatPresent: boolean
    pineconeBlockHash: string | null
  }
}

export type WhyThisDraftRequest =
  | { mode: 'inputs'; queueId: string; subject?: string | null }
  | {
      mode: 'preview'
      leadId: number
      leadName?: string
      channel: OutreachChannel
      templateKey: string
    }

interface WhyThisDraftModalProps {
  request: WhyThisDraftRequest | null
  onClose: () => void
}

export default function WhyThisDraftModal({
  request,
  onClose,
}: WhyThisDraftModalProps) {
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [inputsData, setInputsData] = useState<DraftInputsResponse | null>(null)
  const [previewData, setPreviewData] = useState<PreviewPromptResponse | null>(null)
  const [copied, setCopied] = useState(false)

  useEffect(() => {
    if (!request) {
      setInputsData(null)
      setPreviewData(null)
      setError(null)
      setCopied(false)
      return
    }

    let cancelled = false
    async function load() {
      setLoading(true)
      setError(null)
      setInputsData(null)
      setPreviewData(null)
      setCopied(false)

      try {
        const session = await getCurrentSession()
        if (!session) {
          if (!cancelled) setError('Not signed in.')
          return
        }
        const headers = { Authorization: `Bearer ${session.access_token}` }

        // We just checked that `request` is non-null above (returns early
        // otherwise) — narrow it for TS in this async closure.
        const req = request!
        if (req.mode === 'inputs') {
          const r = await fetch(
            `/api/admin/outreach/drafts/${req.queueId}/inputs`,
            { headers },
          )
          const json = await r.json()
          if (!r.ok) {
            if (!cancelled) setError(json?.error || 'Failed to load draft trace.')
            return
          }
          if (!cancelled) setInputsData(json as DraftInputsResponse)
        } else {
          const params = new URLSearchParams({
            channel: req.channel,
            templateKey: req.templateKey,
          })
          const r = await fetch(
            `/api/admin/outreach/leads/${req.leadId}/preview-prompt?${params.toString()}`,
            { headers },
          )
          const json = await r.json()
          if (!r.ok) {
            if (!cancelled) setError(json?.error || 'Failed to assemble preview prompt.')
            return
          }
          if (!cancelled) setPreviewData(json as PreviewPromptResponse)
        }
      } catch (e) {
        if (!cancelled) setError(e instanceof Error ? e.message : 'Unexpected error')
      } finally {
        if (!cancelled) setLoading(false)
      }
    }

    void load()
    return () => {
      cancelled = true
    }
  }, [request])

  const open = request !== null

  const headerTitle =
    request?.mode === 'inputs'
      ? 'Why this draft?'
      : request?.mode === 'preview'
        ? 'Preview prompt'
        : ''

  const headerSubtitle =
    request?.mode === 'inputs'
      ? request.subject || 'Draft trace'
      : request?.mode === 'preview'
        ? `${request.channel} · ${request.templateKey}`
        : ''

  return (
    <AnimatePresence>
      {open && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          className="fixed inset-0 z-50 flex justify-end bg-background/60"
          onClick={onClose}
        >
          <motion.div
            initial={{ x: 400 }}
            animate={{ x: 0 }}
            exit={{ x: 400 }}
            onClick={(e) => e.stopPropagation()}
            className="flex w-full max-w-lg flex-col border-l border-silicon-slate bg-imperial-navy shadow-xl"
          >
            <div className="flex items-start justify-between border-b border-silicon-slate p-4">
              <div className="min-w-0">
                <h3 className="text-base font-semibold text-foreground">{headerTitle}</h3>
                <p className="truncate text-xs text-muted-foreground" title={headerSubtitle}>
                  {headerSubtitle}
                </p>
              </div>
              <button
                type="button"
                onClick={onClose}
                aria-label="Close"
                className="rounded-lg bg-silicon-slate/50 p-2 text-muted-foreground hover:bg-silicon-slate"
              >
                <X size={16} />
              </button>
            </div>

            <div className="flex-1 overflow-y-auto p-4">
              {loading && (
                <div className="flex items-center justify-center py-12 text-muted-foreground">
                  <Loader2 size={20} className="mr-2 animate-spin" />
                  <span className="text-sm">Loading…</span>
                </div>
              )}

              {!loading && error && (
                <div className="rounded-md border border-red-500/30 bg-red-950/30 p-3 text-sm text-red-200">
                  {error}
                </div>
              )}

              {!loading && !error && request?.mode === 'inputs' && inputsData && (
                <InputsView data={inputsData} />
              )}

              {!loading && !error && request?.mode === 'preview' && previewData && (
                <PreviewView
                  data={previewData}
                  copied={copied}
                  onCopy={async () => {
                    try {
                      await navigator.clipboard.writeText(previewData.systemPrompt)
                      setCopied(true)
                      window.setTimeout(() => setCopied(false), 1500)
                    } catch {
                      // Clipboard can fail in cross-origin / iframe contexts.
                      // Silent here — admins can still select the text manually.
                    }
                  }}
                />
              )}
            </div>
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>
  )
}

function InputsView({ data }: { data: DraftInputsResponse }) {
  const inputs = data.generationInputs
  return (
    <div className="space-y-4 text-sm">
      <KvSection title="Draft">
        <KvRow k="Status" v={data.status} />
        <KvRow k="Channel" v={data.channel} />
        <KvRow k="Sequence step" v={String(data.sequenceStep)} />
        <KvRow k="Created" v={new Date(data.createdAt).toLocaleString()} />
        {data.generationPromptSummary && (
          <KvRow k="Prompt summary" v={data.generationPromptSummary} />
        )}
      </KvSection>

      {inputs ? (
        <>
          <KvSection title="Prompt + model">
            <KvRow k="Template key" v={inputs.template_key ?? '—'} />
            <KvRow
              k="Prompt version"
              v={inputs.prompt_version != null ? String(inputs.prompt_version) : '—'}
            />
            <KvRow k="Model" v={inputs.model ?? data.generationModel ?? '—'} />
            <KvRow k="Provider" v={inputs.provider ?? '—'} />
            <KvRow
              k="Temperature"
              v={inputs.temperature != null ? String(inputs.temperature) : '—'}
            />
            <KvRow
              k="Max tokens"
              v={inputs.max_tokens != null ? String(inputs.max_tokens) : '—'}
            />
          </KvSection>

          <KvSection title="Context blocks">
            <KvRow
              k="Research brief"
              v={`${inputs.research_brief_chars ?? 0} chars`}
            />
            <KvRow
              k="Social proof"
              v={`${inputs.social_proof_chars ?? 0} chars`}
            />
            <KvRow
              k="Meeting summary"
              v={inputs.meeting_summary_present ? 'present' : 'none'}
            />
            <KvRow
              k="Meeting action items"
              v={`${inputs.meeting_action_items_chars ?? 0} chars`}
            />
            <KvRow
              k="Pinecone RAG"
              v={`${inputs.pinecone_chars ?? 0} chars`}
            />
            <KvRow
              k="Prior site chat"
              v={inputs.prior_chat_present ? 'present' : 'none'}
            />
            {inputs.pinecone_block_hash && (
              <KvRow
                k="RAG block fingerprint"
                v={inputs.pinecone_block_hash}
                mono
              />
            )}
          </KvSection>
        </>
      ) : (
        <div className="rounded-md border border-amber-500/30 bg-amber-950/20 p-3 text-xs text-amber-100/85">
          Trace not recorded for this draft. Earlier drafts (and any produced by
          the deprecated n8n workflow) predate the Phase 2 generation_inputs
          column. Trigger a fresh generate to capture a full trace.
        </div>
      )}
    </div>
  )
}

function PreviewView({
  data,
  copied,
  onCopy,
}: {
  data: PreviewPromptResponse
  copied: boolean
  onCopy: () => void
}) {
  return (
    <div className="space-y-4 text-sm">
      <KvSection title="Prompt + model">
        <KvRow k="Template" v={data.promptName ?? data.templateKey} />
        <KvRow k="Template key" v={data.templateKey} />
        <KvRow
          k="Prompt version"
          v={data.promptVersion != null ? String(data.promptVersion) : '—'}
        />
        <KvRow k="Channel" v={data.channel} />
        <KvRow k="Model" v={data.model} />
        <KvRow k="Provider" v={data.provider} />
        <KvRow k="Temperature" v={String(data.temperature)} />
        <KvRow k="Max tokens" v={String(data.maxTokens)} />
      </KvSection>

      <KvSection title="Context blocks">
        <KvRow
          k="Research brief"
          v={`${data.contextSizes.researchBriefChars} chars`}
        />
        <KvRow
          k="Social proof"
          v={`${data.contextSizes.socialProofChars} chars`}
        />
        <KvRow
          k="Meeting snippet"
          v={`${data.contextSizes.meetingSnippetChars} chars`}
        />
        <KvRow
          k="Meeting action items"
          v={`${data.contextSizes.meetingActionItemsChars} chars`}
        />
        <KvRow
          k="Pinecone RAG"
          v={`${data.contextSizes.pineconeChars} chars`}
        />
        <KvRow
          k="Prior site chat"
          v={data.contextSizes.priorChatPresent ? 'present' : 'none'}
        />
        {data.contextSizes.pineconeBlockHash && (
          <KvRow
            k="RAG block fingerprint"
            v={data.contextSizes.pineconeBlockHash}
            mono
          />
        )}
      </KvSection>

      <div>
        <div className="mb-1.5 flex items-center justify-between">
          <h4 className="text-xs font-medium uppercase tracking-wide text-muted-foreground">
            Assembled system prompt
          </h4>
          <button
            type="button"
            onClick={onCopy}
            className="inline-flex items-center gap-1 rounded-md border border-silicon-slate/80 bg-silicon-slate/30 px-2 py-1 text-[11px] text-foreground hover:bg-silicon-slate/50"
            aria-label="Copy system prompt"
          >
            {copied ? <Check size={12} /> : <Copy size={12} />}
            {copied ? 'Copied' : 'Copy'}
          </button>
        </div>
        <pre className="max-h-[40vh] overflow-auto whitespace-pre-wrap rounded-md border border-silicon-slate/80 bg-background/40 p-3 font-mono text-[11px] leading-relaxed text-foreground/90">
{data.systemPrompt}
        </pre>
      </div>

      <div>
        <h4 className="mb-1.5 text-xs font-medium uppercase tracking-wide text-muted-foreground">
          User message
        </h4>
        <pre className="overflow-auto whitespace-pre-wrap rounded-md border border-silicon-slate/80 bg-background/40 p-3 font-mono text-[11px] leading-relaxed text-foreground/90">
{data.userPrompt}
        </pre>
      </div>
    </div>
  )
}

function KvSection({
  title,
  children,
}: {
  title: string
  children: React.ReactNode
}) {
  return (
    <div>
      <h4 className="mb-1.5 text-xs font-medium uppercase tracking-wide text-muted-foreground">
        {title}
      </h4>
      <div className="overflow-hidden rounded-md border border-silicon-slate/80 bg-background/30">
        {children}
      </div>
    </div>
  )
}

function KvRow({ k, v, mono }: { k: string; v: string; mono?: boolean }) {
  return (
    <div className="flex items-center justify-between gap-2 border-b border-silicon-slate/30 px-3 py-1.5 text-[12px] last:border-b-0">
      <span className="text-muted-foreground">{k}</span>
      <span
        className={`min-w-0 truncate text-right text-foreground ${mono ? 'font-mono text-[11px]' : ''}`}
        title={v}
      >
        {v}
      </span>
    </div>
  )
}
