/**
 * Slack notifications for in-app outreach generation.
 *
 * Replaces the Slack node that lived inside WF-CLG-002 (n8n) so that drafts
 * generated by `lib/outreach-queue-generator.ts` still ping #outreach for
 * human review. Fire-and-forget — never throws, never blocks the API
 * response.
 *
 * Configure with `SLACK_OUTREACH_DRAFT_WEBHOOK_URL` (Slack Incoming Webhook).
 * If the env var is unset, this is a silent no-op so local/dev environments
 * keep working.
 */

import type { OutreachChannel } from '@/lib/constants/prompt-keys'

interface OutreachDraftSlackPayload {
  contactId: number
  contactName?: string | null
  contactEmail?: string | null
  channel: OutreachChannel
  templateKey: string | null
  queueId: string
}

/** Returns the admin URL for the outreach review page, with the lead pinned. */
function buildReviewUrl(contactId: number): string | null {
  const base =
    process.env.NEXT_PUBLIC_BASE_URL ||
    process.env.ADMIN_URL ||
    process.env.NEXT_PUBLIC_SITE_URL ||
    null
  if (!base) return null
  const trimmed = base.replace(/\/$/, '')
  return `${trimmed}/admin/outreach?contactId=${contactId}`
}

export async function notifyOutreachDraftReady(
  params: OutreachDraftSlackPayload,
): Promise<boolean> {
  const webhookUrl = process.env.SLACK_OUTREACH_DRAFT_WEBHOOK_URL
  if (!webhookUrl || !webhookUrl.startsWith('https://')) {
    return false
  }

  const name = params.contactName?.trim() || 'Unknown lead'
  const email = params.contactEmail?.trim() || '(no email)'
  const channelLabel = params.channel === 'linkedin' ? 'LinkedIn' : 'Email'
  const reviewUrl = buildReviewUrl(params.contactId)

  const lines = [
    `*New ${channelLabel} draft ready for review*`,
    `*Contact:* ${name} | ${email} (lead #${params.contactId})`,
    `*Template:* ${params.templateKey ?? 'default'}`,
    `*Queue ID:* ${params.queueId}`,
  ]
  if (reviewUrl) {
    lines.push(`*Review:* ${reviewUrl}`)
  }

  try {
    const res = await fetch(webhookUrl, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ text: lines.join('\n') }),
    })
    if (!res.ok) {
      console.warn(
        '[slack-outreach-notification] webhook failed:',
        res.status,
        await res.text().catch(() => ''),
      )
      return false
    }
    return true
  } catch (err) {
    console.warn(
      '[slack-outreach-notification] webhook error:',
      err instanceof Error ? err.message : err,
    )
    return false
  }
}
