/**
 * Build-time script: reads docs and README, writes lib/chatbot-knowledge-content.generated.ts.
 * Run before `next build` so the serverless bundle includes the knowledge (no runtime fs on Vercel).
 */

import { readFile, writeFile } from 'fs/promises'
import path from 'path'

const SOURCES: { path: string; sectionTitle?: string }[] = [
  { path: 'docs/chatbot-products-and-services-overview.md', sectionTitle: 'What AmaduTown Offers (products and services)' },
  { path: 'docs/user-help-guide.md', sectionTitle: 'User Help Guide' },
  { path: 'docs/admin-sales-lead-pipeline-sop.md', sectionTitle: 'Admin & Sales Lead Pipeline (overview)' },
  { path: 'README.md', sectionTitle: 'Project overview' },
]

async function main() {
  const cwd = process.cwd()
  const parts: string[] = []

  for (const entry of SOURCES) {
    const absolutePath = path.join(cwd, entry.path)
    try {
      const content = await readFile(absolutePath, 'utf-8')
      const sectionHeader = entry.sectionTitle
        ? `## Source: ${entry.sectionTitle}\n\n`
        : `## Source: ${entry.path}\n\n`
      parts.push(sectionHeader + content.trim())
    } catch (err) {
      console.warn(`Chatbot knowledge: skipped ${entry.path}`, err instanceof Error ? err.message : err)
    }
  }

  if (parts.length === 0) {
    console.error('No knowledge sources could be read. Ensure docs/ and README.md exist.')
    process.exit(1)
  }

  const body = parts.join('\n\n---\n\n')
  const outPath = path.join(cwd, 'lib', 'chatbot-knowledge-content.generated.ts')
  const escaped = JSON.stringify(body)
  const fileContent = `// Generated by scripts/build-chatbot-knowledge.ts — do not edit manually.
export const CHATBOT_KNOWLEDGE_BODY: string = ${escaped};
`

  await writeFile(outPath, fileContent, 'utf-8')
  console.log(`Wrote ${outPath} (${body.length} chars from ${parts.length} source(s)).`)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
